### ISSUE TITLE
Equivalent function to socket.join ?

### ISSUE THREAD

**Issue by FifineHex** [bminer/ws-server-wrapper#4]
I was using SocketIO but I still wanted more performance for my game actions _(store, rooms, inventory and etc)_, so I discovered this wonderful library and your work on that project that is very good.

I wanted something similar to the _"socket.join"_ function because I need to send information only to people connected in that room **(and I also believe that this way would not send unnecessary packet to other clients that are not in the room, room ids are dynamically generated)**

I looked in the documentation and did not find anything that would serve this, sorry if I'm wrong

**Sorry for any inconvenience**

**Comment by bminer** [comment]
Good question. Although namespaces are provided by this library, "rooms" that you can join or leave are not implemented.  In my opinion, though, this is easy enough to implement yourself...

```javascript
const wss = new WebSocketServerWrapper(
  new WebSocketServer({port: 3000})
);
// Create an Object. Keys are room names, values are Sets of Sockets
const rooms = {}
// Join a room
function joinRoom(name, socket) {
  const room = rooms[name] || new Set()
  rooms[name] = room
  room.add(socket)
}
// Leave a room and clean up the room when it's empty
function leaveRoom(name, socket) {
  const room = rooms[name]
  if(room) {
    room.delete(socket)
    if(room.size === 0) {
      delete rooms[name]
    }
  }
}
```

The above code isn't tested or anything, but at least it gives you an idea.

I'm closing this issue for now, but please feel free to post back here!  Happy coding!

**Comment by FifineHex** [comment]
this code works perfectly

I did a small function to send to all who are inside the room, it may be useful for some documentation
my final code:

```
const rooms = {};

function joinRoom(name, socket) {
    const room = rooms[name] || new Set()
    rooms[name] = room
    room.add(socket)
}

function leaveRoom(name, socket) {
    const room = rooms[name]
    if(room) {
      room.delete(socket)
      if(room.size === 0) {
        delete rooms[name]
      }
    }
}

WS.on("connection", function (client) {
    function SendTo(room, event, data) {
        for (const value of rooms[room]) {
            value.emit(event, data);
        }
    }

   joinRoom("lobby", client);
   SendTo("lobby", "userlist", {usr: 134, ....})
});
```
